### ISSUE TITLE
SSLHandshakeException on java 8

### ISSUE THREAD

**Issue by liketic** [splunk/splunk-sdk-java#113]
java version: `1.8.0_101`
error: 
`
Exception in thread "main" java.lang.RuntimeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at com.splunk.HttpService.send(HttpService.java:451)
	at com.splunk.Service.send(Service.java:1295)
	at com.splunk.HttpService.post(HttpService.java:348)
	at com.splunk.Service.login(Service.java:1124)
	at com.splunk.Service.login(Service.java:1103)
	at com.splunk.Service.connect(Service.java:189)
	at com.splunk.examples.search_saved.Program.main(Program.java:61)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.Handshaker.activate(Handshaker.java:503)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1482)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1351)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.splunk.HttpService.send(HttpService.java:445)
	... 6 more
`
More related info:
 https://answers.splunk.com/answers/209379/no-appropriate-protocol-protocol-is-disabled-or-ci.html
https://blogs.oracle.com/java-platform-group/diagnosing-tls,-ssl,-and-https

**Comment by shakeelmohamed** [comment]
Filed DVPL-7284 to address this

**Comment by tdhellmann** [comment]
We've merged a fix for this issue - please let us know if you're still having difficulties.

**Comment by mviramgama** [comment]
I added splunk plugin today in Eclipse. Still getting issue.
Exception in thread "main" java.lang.RuntimeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at com.splunk.HttpService.send(HttpService.java:345)
	at com.splunk.Service.send(Service.java:1278)
	at com.splunk.HttpService.post(HttpService.java:243)
	at com.splunk.Service.login(Service.java:1109)
	at com.splunk.Service.login(Service.java:1089)
	at com.splunk.Service.connect(Service.java:183)
	at Program.main(Program.java:27)

**Comment by shakeelmohamed** [comment]
@mviramgama have you tried using TLS, see the `ssl_protocols` for examples of how to do so https://github.com/splunk/splunk-sdk-java/blob/master/examples/com/splunk/examples/ssl_protocols/Program.java

**Comment by mviramgama** [comment]
That is really good test program. But unfortunately it didn't work for me.

```
Your Java version is: 8
Now trying to connect to Splunk using SSLv3
	 Failure! 
Now trying to connect to Splunk using TLSv1
	 Failure! 
Now trying to connect to Splunk using TLSv1.1
	 Failure! 
Now trying to connect to Splunk using TLSv1.2
	 Failure! 
Now trying to connect to Splunk using a custom SSL only SSLSocketFactory
	 Failure!
Now trying to connect to Splunk using a custom TLS only SSLSocketFactory
	 Failure!
```

**Comment by mviramgama** [comment]
Finally it worked. My mistake was that I was setting port value as 443 SSL. When I removed that port setting then TLSv1, TLSv1.1, TLSv1.2, custom all are working.

Thanks shakeelmohamed  for your valuable help. Appreciated.
